module.exports = [
    // 'origin',
    '',
    'genesis',
    'rules',
    // 'fee',
    // 'auto-farming',
    // 'airdrop',
    // 'fomo',
    // 'lp',
    // 'fund',
    // 'burn',
    'dapp',
    'faq',
]
